optimization_config:
  n_optimization_steps: 16
  init_lr_t: 0.05
  init_lr_r: 0.05
  decay_t: 0.9
  decay_r: 0.09
dataset:
  path: "/home/jovyan/data/storage/data/language/simple"
  n_perspectives: 50